#Phase space actor
/gate/actor/addActor PhaseSpaceActor               frite_colli2_before_phasespaceactor
/gate/actor/frite_colli2_before_phasespaceactor/save                     output/frite_colli2_before_phasespaceactor.root
/gate/actor/frite_colli2_before_phasespaceactor/attachTo                 frite_colli2_before

/gate/actor/frite_colli2_before_phasespaceactor/enableEkine              true
/gate/actor/frite_colli2_before_phasespaceactor/enableXPosition          true
/gate/actor/frite_colli2_before_phasespaceactor/enableYPosition          true
/gate/actor/frite_colli2_before_phasespaceactor/enableZPosition          false
/gate/actor/frite_colli2_before_phasespaceactor/enableXDirection         false
/gate/actor/frite_colli2_before_phasespaceactor/enableYDirection         false
/gate/actor/frite_colli2_before_phasespaceactor/enableZDirection         false
/gate/actor/frite_colli2_before_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_colli2_before_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_colli2_before_phasespaceactor/enableParticleName       false
/gate/actor/frite_colli2_before_phasespaceactor/enableWeight             false
/gate/actor/frite_colli2_before_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_colli2_before_phasespaceactor/particleFilter/addParticle      proton
/gate/actor/frite_colli2_before_phasespaceactor/enableCharge             false
/gate/actor/frite_colli2_before_phasespaceactor/enableMass             false
/gate/actor/frite_colli2_before_phasespaceactor/enableTOut             false
/gate/actor/frite_colli2_before_phasespaceactor/enableTProd             false


#Phase space actor
/gate/actor/addActor PhaseSpaceActor              frite_colli2_after_phasespaceactor
/gate/actor/frite_colli2_after_phasespaceactor/save                     output/frite_colli2_after_phasespaceactor.root
/gate/actor/frite_colli2_after_phasespaceactor/attachTo                 frite_colli2_after

/gate/actor/frite_colli2_after_phasespaceactor/enableEkine              true
/gate/actor/frite_colli2_after_phasespaceactor/enableXPosition          true
/gate/actor/frite_colli2_after_phasespaceactor/enableYPosition          true
/gate/actor/frite_colli2_after_phasespaceactor/enableZPosition          false
/gate/actor/frite_colli2_after_phasespaceactor/enableXDirection         false
/gate/actor/frite_colli2_after_phasespaceactor/enableYDirection         false
/gate/actor/frite_colli2_after_phasespaceactor/enableZDirection         false
/gate/actor/frite_colli2_after_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_colli2_after_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_colli2_after_phasespaceactor/enableParticleName       false
/gate/actor/frite_colli2_after_phasespaceactor/enableWeight             false
/gate/actor/frite_colli2_after_phasespaceactor/enablePrimaryEnergy      false
/gate/actor/frite_colli2_after_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_colli2_after_phasespaceactor/particleFilter/addParticle      proton

/gate/actor/frite_colli2_after_phasespaceactor/enableCharge             false
/gate/actor/frite_colli2_after_phasespaceactor/enableMass             false
/gate/actor/frite_colli2_after_phasespaceactor/enableTOut             false
/gate/actor/frite_colli2_after_phasespaceactor/enableTProd             false

###################### Collimateur2 ######################################################################

###################### Ionizationchamber ######################################################################

#Phase space actor
/gate/actor/addActor PhaseSpaceActor              frite_Ionizationchamber_before_phasespaceactor
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/save                     output/frite_Ionizationchamber_before_phasespaceactor.root
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/attachTo                 Ionizationchamber

/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableEkine              true
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableXPosition          true
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableYPosition          true
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableZPosition          false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableXDirection         false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableYDirection         false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableZDirection         false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableParticleName       false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableWeight             false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/particleFilter/addParticle      proton

/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableCharge             false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableMass             false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableTOut             false
/gate/actor/frite_Ionizationchamber_before_phasespaceactor/enableTProd             false

#Phase space actor
/gate/actor/addActor PhaseSpaceActor             frite_Ionizationchamber_after_phasespaceactor
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/save                     output/frite_Ionizationchamber_after_phasespaceactor.root
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/attachTo                 Ionizationchamber

/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableEkine              true
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableXPosition          true
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableYPosition          true
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableZPosition          false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableXDirection         false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableYDirection         false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableZDirection         false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableParticleName       false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableWeight             false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/particleFilter/addParticle      proton
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/storeOutgoingParticles true

/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableCharge             false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableMass             false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableTOut             false
/gate/actor/frite_Ionizationchamber_after_phasespaceactor/enableTProd             false

###################### Ionizationchamber ######################################################################

###################### Lightdetector ######################################################################

#Phase space actor
/gate/actor/addActor PhaseSpaceActor             frite_Lightdetector_before_phasespaceactor
/gate/actor/frite_Lightdetector_before_phasespaceactor/save                     output/frite_Lightdetector_before_phasespaceactor.root
/gate/actor/frite_Lightdetector_before_phasespaceactor/attachTo                 Alu_in

/gate/actor/frite_Lightdetector_before_phasespaceactor/enableEkine              true
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableXPosition          true
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableYPosition          true
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableZPosition          false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableXDirection         false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableYDirection         false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableZDirection         false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableParticleName       false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableWeight             false
/gate/actor/frite_Lightdetector_before_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_Lightdetector_before_phasespaceactor/particleFilter/addParticle      proton

/gate/actor/frite_Lightdetector_before_phasespaceactor/enableCharge             false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableMass             false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableTOut             false
/gate/actor/frite_Lightdetector_before_phasespaceactor/enableTProd             false


#Phase space actor
/gate/actor/addActor PhaseSpaceActor             frite_Lightdetector_after_phasespaceactor
/gate/actor/frite_Lightdetector_after_phasespaceactor/save                     output/frite_Lightdetector_after_phasespaceactor.root
/gate/actor/frite_Lightdetector_after_phasespaceactor/attachTo                 Alu_out

/gate/actor/frite_Lightdetector_after_phasespaceactor/enableEkine              true
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableXPosition          true
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableYPosition          true
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableZPosition          false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableXDirection         false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableYDirection         false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableZDirection         false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableParticleName       false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableWeight             false
/gate/actor/frite_Lightdetector_after_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_Lightdetector_after_phasespaceactor/particleFilter/addParticle      proton
/gate/actor/frite_Lightdetector_after_phasespaceactor/storeOutgoingParticles true

/gate/actor/frite_Lightdetector_after_phasespaceactor/enableCharge             false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableMass             false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableTOut             false
/gate/actor/frite_Lightdetector_after_phasespaceactor/enableTProd             false

###################### Lightdetector ######################################################################


###################### Collimateur1 ######################################################################

#Phase space actor
/gate/actor/addActor PhaseSpaceActor               frite_colli_before_phasespaceactor
/gate/actor/frite_colli_before_phasespaceactor/save                     output/frite_colli_before_phasespaceactor.root
/gate/actor/frite_colli_before_phasespaceactor/attachTo                 frite_colli_before

/gate/actor/frite_colli_before_phasespaceactor/enableEkine              true
/gate/actor/frite_colli_before_phasespaceactor/enableXPosition          true
/gate/actor/frite_colli_before_phasespaceactor/enableYPosition          true
/gate/actor/frite_colli_before_phasespaceactor/enableZPosition          false
/gate/actor/frite_colli_before_phasespaceactor/enableXDirection         false
/gate/actor/frite_colli_before_phasespaceactor/enableYDirection         false
/gate/actor/frite_colli_before_phasespaceactor/enableZDirection         false
/gate/actor/frite_colli_before_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_colli_before_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_colli_before_phasespaceactor/enableParticleName       false
/gate/actor/frite_colli_before_phasespaceactor/enableWeight             false
/gate/actor/frite_colli_before_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_colli_before_phasespaceactor/particleFilter/addParticle      proton

/gate/actor/frite_colli_before_phasespaceactor/enableCharge             false
/gate/actor/frite_colli_before_phasespaceactor/enableMass             false
/gate/actor/frite_colli_before_phasespaceactor/enableTOut             false
/gate/actor/frite_colli_before_phasespaceactor/enableTProd             false


#Phase space actor
/gate/actor/addActor PhaseSpaceActor              frite_colli_after_phasespaceactor
/gate/actor/frite_colli_after_phasespaceactor/save                     output/frite_colli_after_phasespaceactor.root
/gate/actor/frite_colli_after_phasespaceactor/attachTo                 frite_colli_after

/gate/actor/frite_colli_after_phasespaceactor/enableEkine              true
/gate/actor/frite_colli_after_phasespaceactor/enableXPosition          true
/gate/actor/frite_colli_after_phasespaceactor/enableYPosition          true
/gate/actor/frite_colli_after_phasespaceactor/enableZPosition          false
/gate/actor/frite_colli_after_phasespaceactor/enableXDirection         false
/gate/actor/frite_colli_after_phasespaceactor/enableYDirection         false
/gate/actor/frite_colli_after_phasespaceactor/enableZDirection         false
/gate/actor/frite_colli_after_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_colli_after_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_colli_after_phasespaceactor/enableParticleName       false
/gate/actor/frite_colli_after_phasespaceactor/enableWeight             false
/gate/actor/frite_colli_after_phasespaceactor/enablePrimaryEnergy      false
/gate/actor/frite_colli_after_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_colli_after_phasespaceactor/particleFilter/addParticle      proton

/gate/actor/frite_colli_after_phasespaceactor/enableCharge             false
/gate/actor/frite_colli_after_phasespaceactor/enableMass             false
/gate/actor/frite_colli_after_phasespaceactor/enableTOut             false
/gate/actor/frite_colli_after_phasespaceactor/enableTProd             false

###################### Collimateur1 ######################################################################


###################### Kapton ######################################################################

#Phase space actor
/gate/actor/addActor PhaseSpaceActor             frite_kapton_phasespaceactor
/gate/actor/frite_kapton_phasespaceactor/save                     output/frite_kapton_phasespaceactor.root
/gate/actor/frite_kapton_phasespaceactor/attachTo                 kapton

/gate/actor/frite_kapton_phasespaceactor/enableEkine              true
/gate/actor/frite_kapton_phasespaceactor/enableXPosition          true
/gate/actor/frite_kapton_phasespaceactor/enableYPosition          true
/gate/actor/frite_kapton_phasespaceactor/enableZPosition          false
/gate/actor/frite_kapton_phasespaceactor/enableXDirection         false
/gate/actor/frite_kapton_phasespaceactor/enableYDirection         false
/gate/actor/frite_kapton_phasespaceactor/enableZDirection         false
/gate/actor/frite_kapton_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_kapton_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_kapton_phasespaceactor/enableParticleName       false
/gate/actor/frite_kapton_phasespaceactor/enableWeight             false
/gate/actor/frite_kapton_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_kapton_phasespaceactor/particleFilter/addParticle      proton

/gate/actor/frite_kapton_phasespaceactor/enableCharge             false
/gate/actor/frite_kapton_phasespaceactor/enableMass             false
/gate/actor/frite_kapton_phasespaceactor/enableTOut             false
/gate/actor/frite_kapton_phasespaceactor/enableTProd             false


#Phase space actor
/gate/actor/addActor PhaseSpaceActor             frite_Kapton_after_phasespaceactor
/gate/actor/frite_Kapton_after_phasespaceactor/save                     output/frite_Kapton_after_phasespaceactor.root
/gate/actor/frite_Kapton_after_phasespaceactor/attachTo                 kapton

/gate/actor/frite_Kapton_after_phasespaceactor/enableEkine              true
/gate/actor/frite_Kapton_after_phasespaceactor/enableXPosition          true
/gate/actor/frite_Kapton_after_phasespaceactor/enableYPosition          true
/gate/actor/frite_Kapton_after_phasespaceactor/enableZPosition          false
/gate/actor/frite_Kapton_after_phasespaceactor/enableXDirection         false
/gate/actor/frite_Kapton_after_phasespaceactor/enableYDirection         false
/gate/actor/frite_Kapton_after_phasespaceactor/enableZDirection         false
/gate/actor/frite_Kapton_after_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_Kapton_after_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_Kapton_after_phasespaceactor/enableParticleName       false
/gate/actor/frite_Kapton_after_phasespaceactor/enableWeight             false
/gate/actor/frite_Kapton_after_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_Kapton_after_phasespaceactor/particleFilter/addParticle      proton
/gate/actor/frite_Kapton_after_phasespaceactor/storeOutgoingParticles true

/gate/actor/frite_Kapton_after_phasespaceactor/enableCharge             false
/gate/actor/frite_Kapton_after_phasespaceactor/enableMass             false
/gate/actor/frite_Kapton_after_phasespaceactor/enableTOut             false
/gate/actor/frite_Kapton_after_phasespaceactor/enableTProd             false

###################### Kapton ######################################################################
