#Phase space actor
/gate/actor/addActor PhaseSpaceActor              frite_colli_after_phasespaceactor
/gate/actor/frite_colli_after_phasespaceactor/save                     output/frite_colli_after_phasespaceactor.root
/gate/actor/frite_colli_after_phasespaceactor/attachTo                 frite_colli_after
/gate/actor/frite_colli_after_phasespaceactor/enableEkine              true
/gate/actor/frite_colli_after_phasespaceactor/enableXPosition          true
/gate/actor/frite_colli_after_phasespaceactor/enableYPosition          true
/gate/actor/frite_colli_after_phasespaceactor/enableZPosition          false
/gate/actor/frite_colli_after_phasespaceactor/enableXDirection         false
/gate/actor/frite_colli_after_phasespaceactor/enableYDirection         false
/gate/actor/frite_colli_after_phasespaceactor/enableZDirection         false
/gate/actor/frite_colli_after_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_colli_after_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_colli_after_phasespaceactor/enableParticleName       false
/gate/actor/frite_colli_after_phasespaceactor/enableWeight             false
/gate/actor/frite_colli_after_phasespaceactor/enablePrimaryEnergy      false
/gate/actor/frite_colli_after_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_colli_after_phasespaceactor/particleFilter/addParticle      proton

/gate/actor/frite_colli_after_phasespaceactor/enableCharge             false
/gate/actor/frite_colli_after_phasespaceactor/enableMass             false
/gate/actor/frite_colli_after_phasespaceactor/enableTOut             false
/gate/actor/frite_colli_after_phasespaceactor/enableTProd             false




#Phase space actor
/gate/actor/addActor PhaseSpaceActor             frite_Kapton_after_phasespaceactor
/gate/actor/frite_Kapton_after_phasespaceactor/save                     output/frite_Kapton_after_phasespaceactor.root
/gate/actor/frite_Kapton_after_phasespaceactor/attachTo                 kapton
/gate/actor/frite_Kapton_after_phasespaceactor/enableEkine              true
/gate/actor/frite_Kapton_after_phasespaceactor/enableXPosition          true
/gate/actor/frite_Kapton_after_phasespaceactor/enableYPosition          true
/gate/actor/frite_Kapton_after_phasespaceactor/enableZPosition          false
/gate/actor/frite_Kapton_after_phasespaceactor/enableXDirection         false
/gate/actor/frite_Kapton_after_phasespaceactor/enableYDirection         false
/gate/actor/frite_Kapton_after_phasespaceactor/enableZDirection         false
/gate/actor/frite_Kapton_after_phasespaceactor/enableProductionVolume   false
/gate/actor/frite_Kapton_after_phasespaceactor/enableProductionProcess  false
/gate/actor/frite_Kapton_after_phasespaceactor/enableParticleName       false
/gate/actor/frite_Kapton_after_phasespaceactor/enableWeight             false
/gate/actor/frite_Kapton_after_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_Kapton_after_phasespaceactor/particleFilter/addParticle      proton
/gate/actor/frite_Kapton_after_phasespaceactor/storeOutgoingParticles true

/gate/actor/frite_Kapton_after_phasespaceactor/enableCharge             false
/gate/actor/frite_Kapton_after_phasespaceactor/enableMass             false
/gate/actor/frite_Kapton_after_phasespaceactor/enableTOut             false
/gate/actor/frite_Kapton_after_phasespaceactor/enableTProd             false
