#Phase space actor

#Phase space actor
/gate/actor/addActor PhaseSpaceActor              frite_colli_after_phasespaceactor
/gate/actor/frite_colli_after_phasespaceactor/save                     output/frite_colli_after_phasespaceactor.root
/gate/actor/frite_colli_after_phasespaceactor/attachTo                 frite_colli_after
/gate/actor/frite_colli_after_phasespaceactor/enableEkine              true
/gate/actor/frite_colli_after_phasespaceactor/enableXPosition          true
/gate/actor/frite_colli_after_phasespaceactor/enableYPosition          true
/gate/actor/frite_colli_after_phasespaceactor/enableZPosition          true
/gate/actor/frite_colli_after_phasespaceactor/enableXDirection         true
/gate/actor/frite_colli_after_phasespaceactor/enableYDirection         true
/gate/actor/frite_colli_after_phasespaceactor/enableZDirection         true
/gate/actor/frite_colli_after_phasespaceactor/enableProductionVolume   true
/gate/actor/frite_colli_after_phasespaceactor/enableProductionProcess  true
/gate/actor/frite_colli_after_phasespaceactor/enableParticleName       true
/gate/actor/frite_colli_after_phasespaceactor/enableWeight             true
/gate/actor/frite_colli_after_phasespaceactor/enablePrimaryEnergy      true
/gate/actor/frite_colli_after_phasespaceactor/addFilter                       particleFilter
/gate/actor/frite_colli_after_phasespaceactor/particleFilter/addParticle      proton


